/**
 * JSON Schema -> GBNF converter. Produces grammars that (a) pass this
 * package's own linter with zero findings and (b) accept exactly the JSON
 * documents the supported schema subset describes — both properties are
 * enforced by the test suite, which round-trips generated grammars through
 * the bundled match engine.
 *
 * Design choices mirror the converter that ships inside llama.cpp where
 * that matters for interop:
 * - every value rule consumes optional *trailing* whitespace, bounded to
 *   16 characters so a model can never pad forever;
 * - numbers cap their digit runs (16 integer / 16 fraction / 4 exponent
 *   digits) for the same reason;
 * - object properties are emitted in a fixed order: required properties in
 *   declaration order, then optional ones — a grammar cannot express
 *   "any order" without exponential blowup, and fixed order is what
 *   constrained generation needs anyway.
 *
 * Unsupported keywords are collected as notes (never silently dropped);
 * `strict` mode turns any note into a hard failure.
 */

import { quoteLit } from "./print.js";

/** Thrown when a schema cannot be expressed as a grammar at all. */
export class SchemaError extends Error {
  readonly path: string;

  constructor(message: string, path: string) {
    super(`${message} (at ${path})`);
    this.name = "SchemaError";
    this.path = path;
  }
}

export interface ConvertOptions {
  /** Omit all inter-token whitespace rules (single-line, compact JSON). */
  compact?: boolean;
}

export interface ConvertResult {
  /** The generated grammar text, ending in a newline. */
  grammar: string;
  /** One entry per ignored/unsupported keyword occurrence. */
  notes: string[];
}

/** Keywords we recognize but cannot express in a grammar (yet). */
const UNSUPPORTED_KEYWORDS = [
  "pattern",
  "minimum",
  "maximum",
  "exclusiveMinimum",
  "exclusiveMaximum",
  "multipleOf",
  "uniqueItems",
  "contains",
  "minProperties",
  "maxProperties",
  "patternProperties",
  "propertyNames",
  "not",
  "if",
  "then",
  "else",
  "dependentSchemas",
  "dependentRequired",
] as const;

/** Purely descriptive keywords, ignored without a note. */
const METADATA_KEYWORDS = new Set([
  "$schema", "$id", "$comment", "title", "description", "default",
  "examples", "deprecated", "readOnly", "writeOnly", "$defs", "definitions",
]);

const FORMAT_RULES = new Set(["uuid", "date", "time", "date-time"]);

type SchemaObject = Record<string, unknown>;

class Emitter {
  private readonly bodies = new Map<string, string>();
  private readonly order: string[] = [];
  private readonly primitives = new Map<string, string>();
  private readonly refRules = new Map<string, string>();
  readonly notes: string[] = [];
  private readonly compact: boolean;
  private readonly doc: unknown;

  constructor(doc: unknown, options: ConvertOptions) {
    this.doc = doc;
    this.compact = options.compact === true;
    // Reserve the entry-point name before anything else can claim it.
    this.bodies.set("root", "");
    this.order.push("root");
  }

  // --- rule table -------------------------------------------------------

  /** Define a rule, reusing or renaming on collision. Returns the name. */
  private define(base: string, body: string): string {
    let name = base;
    for (let i = 2; this.bodies.has(name); i++) {
      if (this.bodies.get(name) === body) return name; // identical: reuse
      name = `${base}-${i}`;
    }
    this.bodies.set(name, body);
    this.order.push(name);
    return name;
  }

  setRoot(body: string): void {
    this.bodies.set("root", body);
  }

  render(): string {
    const lines = [
      "# JSON Schema -> GBNF, generated by gbnf-doctor. Edit the schema, not this file.",
    ];
    for (const name of this.order) {
      lines.push(`${name} ::= ${this.bodies.get(name) as string}`);
    }
    return lines.join("\n") + "\n";
  }

  private note(message: string, path: string): void {
    const entry = `ignored ${message} at ${path}`;
    if (!this.notes.includes(entry)) this.notes.push(entry);
  }

  // --- shared building blocks --------------------------------------------

  /** Join non-empty parts with single spaces. */
  private seq(...parts: string[]): string {
    return parts.filter((p) => p !== "").join(" ");
  }

  /** The whitespace reference, or nothing in compact mode. */
  private ws(): string {
    if (this.compact) return "";
    return this.primitive("ws");
  }

  /** Wrap an expression in ( ) unless it is already atomic. */
  private group(expr: string): string {
    if (/^[a-zA-Z0-9-]+$/.test(expr)) return expr; // bare rule name
    if (/^"(?:[^"\\]|\\.)*"$/.test(expr)) return expr; // single literal
    return `( ${expr} )`;
  }

  private primitive(name: string): string {
    const existing = this.primitives.get(name);
    if (existing !== undefined) return existing;
    // Reserve the name before building the body: value / object / array
    // are mutually recursive, and the recursion must resolve to the name.
    let final = name;
    for (let i = 2; this.bodies.has(final); i++) final = `${name}-${i}`;
    this.bodies.set(final, ` pending:${name}`);
    this.order.push(final);
    this.primitives.set(name, final);
    this.bodies.set(final, this.primitiveBody(name));
    return final;
  }

  private primitiveBody(name: string): string {
    const ws = name === "ws" ? "" : this.ws();
    switch (name) {
      case "ws":
        // Bounded on purpose: an unbounded trailing [ \t\n]* would let the
        // model pad whitespace forever (and would trip our own W107).
        return "[ \\t\\n\\r]{0,16}";
      case "string-char":
        return '[^"\\\\\\x00-\\x1F] | "\\\\" (["\\\\/bfnrt] | "u" [0-9a-fA-F]{4})';
      case "string":
        return this.seq('"\\""', `${this.primitive("string-char")}*`, '"\\""', ws);
      case "number":
        return this.seq(
          '"-"?',
          "( [0-9] | [1-9] [0-9]{1,15} )",
          '( "." [0-9]{1,16} )?',
          '( [eE] [-+]? [0-9]{1,4} )?',
          ws
        );
      case "integer":
        return this.seq('"-"?', "( [0-9] | [1-9] [0-9]{1,15} )", ws);
      case "boolean":
        return this.seq('( "true" | "false" )', ws);
      case "null":
        return this.seq('"null"', ws);
      case "value":
        return [
          this.primitive("object"),
          this.primitive("array"),
          this.primitive("string"),
          this.primitive("number"),
          this.primitive("boolean"),
          this.primitive("null"),
        ].join(" | ");
      case "object": {
        const kv = this.define(
          "object-kv",
          this.seq(this.primitive("string"), '":"', ws, this.primitive("value"))
        );
        return this.seq('"{"', ws, `( ${kv} ( "," ${this.seq(ws, kv)} )* )?`, '"}"', ws);
      }
      case "array": {
        const value = this.primitive("value");
        return this.seq(
          '"["', ws, `( ${value} ( "," ${this.seq(ws, value)} )* )?`, '"]"', ws
        );
      }
      case "hex":
        return "[0-9a-fA-F]";
      case "uuid": {
        const hex = this.primitive("hex");
        return this.seq(
          '"\\""',
          `${hex}{8} "-" ${hex}{4} "-" ${hex}{4} "-" ${hex}{4} "-" ${hex}{12}`,
          '"\\""',
          ws
        );
      }
      case "date-body":
        return '[0-9]{4} "-" ( "0" [1-9] | "1" [0-2] ) "-" ( "0" [1-9] | [12] [0-9] | "3" [01] )';
      case "time-body":
        return (
          '( [01] [0-9] | "2" [0-3] ) ":" [0-5] [0-9] ":" [0-5] [0-9] ' +
          '( "." [0-9]{1,3} )? ( "Z" | ( "+" | "-" ) ( [01] [0-9] | "2" [0-3] ) ":" [0-5] [0-9] )'
        );
      case "date":
        return this.seq('"\\""', this.primitive("date-body"), '"\\""', ws);
      case "time":
        return this.seq('"\\""', this.primitive("time-body"), '"\\""', ws);
      case "date-time":
        return this.seq(
          '"\\""', this.primitive("date-body"), '"T"',
          this.primitive("time-body"), '"\\""', ws
        );
      /* c8 ignore next 2 */
      default:
        throw new Error(`internal error: unknown primitive "${name}"`);
    }
  }

  // --- schema visitor -----------------------------------------------------

  visit(schema: unknown, path: string, hint: string): string {
    if (schema === true) return this.primitive("value");
    if (schema === false) {
      throw new SchemaError('the "false" schema matches nothing', path);
    }
    if (typeof schema !== "object" || schema === null || Array.isArray(schema)) {
      throw new SchemaError("schema must be an object or a boolean", path);
    }
    const s = schema as SchemaObject;

    for (const kw of UNSUPPORTED_KEYWORDS) {
      if (kw in s) this.note(`"${kw}"`, path);
    }

    if (typeof s["$ref"] === "string") return this.visitRef(s["$ref"], path);
    if ("const" in s) return this.literalFor(s["const"], path);
    if ("enum" in s) return this.visitEnum(s["enum"], path);
    if (Array.isArray(s["allOf"])) return this.visitAllOf(s["allOf"], path, hint);
    const branches = s["anyOf"] ?? s["oneOf"];
    if (Array.isArray(branches)) {
      if (Array.isArray(s["oneOf"]) && Array.isArray(s["anyOf"])) {
        this.note('"oneOf" (anyOf on the same schema takes precedence)', path);
      } else if (Array.isArray(s["oneOf"])) {
        this.note('"oneOf" exclusivity (treated as anyOf — a grammar cannot count matches)', path);
      }
      const list = (Array.isArray(s["anyOf"]) ? s["anyOf"] : s["oneOf"]) as unknown[];
      const exprs = list.map((b, i) =>
        this.group(this.visit(b, `${path}/anyOf/${i}`, `${hint}-alt-${i}`))
      );
      return exprs.join(" | ");
    }

    const type = s["type"];
    if (Array.isArray(type)) {
      const exprs = type.map((t, i) =>
        this.group(this.visit({ ...s, type: t }, `${path}/type/${i}`, `${hint}-${String(t)}`))
      );
      return exprs.join(" | ");
    }
    switch (type) {
      case "string":
        return this.visitString(s, path);
      case "number":
        return this.primitive("number");
      case "integer":
        return this.primitive("integer");
      case "boolean":
        return this.primitive("boolean");
      case "null":
        return this.primitive("null");
      case "object":
        return this.visitObject(s, path, hint);
      case "array":
        return this.visitArray(s, path, hint);
      case undefined:
        // Untyped: infer from structural keywords, else any JSON value.
        if ("properties" in s || "required" in s || "additionalProperties" in s) {
          return this.visitObject(s, path, hint);
        }
        if ("items" in s || "prefixItems" in s) {
          return this.visitArray(s, path, hint);
        }
        return this.primitive("value");
      default:
        throw new SchemaError(`unsupported type "${String(type)}"`, path);
    }
  }

  private visitRef(ref: string, path: string): string {
    if (!ref.startsWith("#")) {
      throw new SchemaError(`only local "#/..." $refs are supported, got "${ref}"`, path);
    }
    const known = this.refRules.get(ref);
    if (known !== undefined) return known; // also breaks $ref cycles
    const target = resolvePointer(this.doc, ref, path);
    const segments = ref.split("/");
    const base = sanitizeName(decodePointerSegment(segments[segments.length - 1] ?? ""));
    // Reserve the name first (with a placeholder no real body can equal)
    // so recursive schemas can refer back to it while it is being built.
    const name = this.define(base, ` pending:${ref}`);
    this.refRules.set(ref, name);
    this.bodies.set(name, this.visit(target, ref, name));
    return name;
  }

  private visitEnum(values: unknown, path: string): string {
    if (!Array.isArray(values) || values.length === 0) {
      throw new SchemaError('"enum" must be a non-empty array', path);
    }
    const exprs = values.map((v, i) => this.literalFor(v, `${path}/enum/${i}`));
    return exprs.length === 1 ? (exprs[0] as string) : `( ${exprs.join(" | ")} )`;
  }

  private visitAllOf(list: unknown[], path: string, hint: string): string {
    const merged: SchemaObject = { type: "object", properties: {}, required: [] };
    const props = merged["properties"] as SchemaObject;
    const required = merged["required"] as string[];
    for (const [i, sub] of list.entries()) {
      if (typeof sub !== "object" || sub === null || Array.isArray(sub)) {
        throw new SchemaError('every "allOf" branch must be an object schema', `${path}/allOf/${i}`);
      }
      const o = sub as SchemaObject;
      const isObjectSchema =
        o["type"] === "object" || "properties" in o || "required" in o;
      if (!isObjectSchema) {
        throw new SchemaError(
          '"allOf" is only supported for object schemas in 0.1.0', `${path}/allOf/${i}`
        );
      }
      const subProps = (o["properties"] ?? {}) as SchemaObject;
      for (const [key, value] of Object.entries(subProps)) {
        if (key in props) this.note(`duplicate property "${key}" in allOf (last wins)`, path);
        props[key] = value;
      }
      for (const r of (o["required"] ?? []) as string[]) {
        if (!required.includes(r)) required.push(r);
      }
    }
    return this.visitObject(merged, path, hint);
  }

  private visitString(s: SchemaObject, path: string): string {
    const min = intOrDefault(s["minLength"], 0, path, '"minLength"');
    const max = "maxLength" in s ? intOrDefault(s["maxLength"], 0, path, '"maxLength"') : null;
    if (max !== null && min > max) {
      throw new SchemaError(`"minLength" ${min} is greater than "maxLength" ${max}`, path);
    }
    const format = s["format"];
    if (typeof format === "string") {
      if (FORMAT_RULES.has(format) && min === 0 && max === null) {
        return this.primitive(format);
      }
      this.note(`"format": "${format}"`, path);
    }
    if (min === 0 && max === null) return this.primitive("string");
    const char = this.primitive("string-char");
    return this.seq('"\\""', `${char}${boundsSuffix(min, max)}`, '"\\""', this.ws());
  }

  private visitObject(s: SchemaObject, path: string, hint: string): string {
    const ws = this.ws();
    const props = (s["properties"] ?? {}) as SchemaObject;
    if (typeof props !== "object" || Array.isArray(props)) {
      throw new SchemaError('"properties" must be an object', path);
    }
    const required = (s["required"] ?? []) as unknown[];
    if (!Array.isArray(required) || required.some((r) => typeof r !== "string")) {
      throw new SchemaError('"required" must be an array of strings', path);
    }
    const names = Object.keys(props);
    for (const r of required as string[]) {
      if (!names.includes(r)) names.push(r); // required-but-unschema'd: any value
    }

    const additional = s["additionalProperties"];
    if (names.length === 0) {
      if (additional === false) return this.seq('"{"', ws, '"}"', ws);
      // Free-form object, with typed values when a schema is given.
      const valueExpr =
        additional === undefined || additional === true
          ? this.primitive("value")
          : this.group(this.visit(additional, `${path}/additionalProperties`, `${hint}-value`));
      const kv = this.define(
        kvName(hint, "extra"),
        this.seq(this.primitive("string"), '":"', ws, valueExpr)
      );
      return this.seq('"{"', ws, `( ${kv} ( "," ${this.seq(ws, kv)} )* )?`, '"}"', ws);
    }
    if (additional !== undefined && additional !== false) {
      this.note('"additionalProperties" alongside "properties" (extra keys are disallowed)', path);
    }

    const requiredSet = new Set(required as string[]);
    const requiredKvs: string[] = [];
    const optionalKvs: string[] = [];
    for (const key of names) {
      const sub = key in props ? props[key] : true;
      const valueExpr = this.visit(sub, `${path}/properties/${key}`, sanitizeName(key));
      const value = /^[a-zA-Z0-9-]+$/.test(valueExpr)
        ? valueExpr
        : this.define(kvName(hint, key), valueExpr);
      const kv = this.seq(quoteLit(JSON.stringify(key)), ws, '":"', ws, value);
      (requiredSet.has(key) ? requiredKvs : optionalKvs).push(kv);
    }

    let body: string;
    if (requiredKvs.length > 0) {
      const parts = [requiredKvs[0] as string];
      for (const kv of requiredKvs.slice(1)) parts.push(this.seq('","', ws, kv));
      for (const kv of optionalKvs) parts.push(`( ${this.seq('","', ws, kv)} )?`);
      body = parts.join(" ");
    } else {
      // All properties optional: any non-empty subset, in declaration order.
      const branches = optionalKvs.map((kv, i) => {
        const tail = optionalKvs
          .slice(i + 1)
          .map((later) => `( ${this.seq('","', ws, later)} )?`);
        return this.seq(kv, ...tail);
      });
      body = `( ${branches.join(" | ")} )?`;
    }
    return this.seq('"{"', ws, body, '"}"', ws);
  }

  private visitArray(s: SchemaObject, path: string, hint: string): string {
    const ws = this.ws();
    const prefixItems = s["prefixItems"];
    if (Array.isArray(prefixItems)) {
      if ("minItems" in s || "maxItems" in s) {
        this.note('"minItems"/"maxItems" together with "prefixItems"', path);
      }
      const exprs = prefixItems.map((sub, i) => {
        const expr = this.visit(sub, `${path}/prefixItems/${i}`, `${hint}-${i}`);
        return /^[a-zA-Z0-9-]+$/.test(expr) ? expr : this.define(`${hint}-${i}`, expr);
      });
      const items = s["items"];
      let rest = "";
      if (items !== false && "items" in s) {
        const extra = this.itemExpr(items, path, hint);
        rest = `( "," ${this.seq(ws, extra)} )*`;
      } else if (!("items" in s)) {
        rest = `( "," ${this.seq(ws, this.primitive("value"))} )*`;
      }
      const parts = [exprs[0] as string];
      for (const e of exprs.slice(1)) parts.push(this.seq('","', ws, e));
      if (rest !== "") parts.push(rest);
      return this.seq('"["', ws, parts.join(" "), '"]"', ws);
    }

    const min = intOrDefault(s["minItems"], 0, path, '"minItems"');
    const max = "maxItems" in s ? intOrDefault(s["maxItems"], 0, path, '"maxItems"') : null;
    if (max !== null && min > max) {
      throw new SchemaError(`"minItems" ${min} is greater than "maxItems" ${max}`, path);
    }
    if (max === 0 || s["items"] === false) {
      if (min > 0) {
        throw new SchemaError("the array can never hold the required minItems", path);
      }
      return this.seq('"["', ws, '"]"', ws); // only the empty array fits
    }
    const item = this.itemExpr(s["items"] ?? true, path, hint);
    const more = `( "," ${this.seq(ws, item)} )`;
    const hi = max === null ? null : max - 1;
    if (min === 0) {
      const tail = hi === 0 ? "" : `${more}${boundsSuffix(0, hi)}`;
      return this.seq('"["', ws, `( ${this.seq(item, tail)} )?`, '"]"', ws);
    }
    const tail = hi === 0 ? "" : `${more}${boundsSuffix(min - 1, hi)}`;
    return this.seq('"["', ws, item, tail, '"]"', ws);
  }

  private itemExpr(schema: unknown, path: string, hint: string): string {
    const expr = this.visit(schema, `${path}/items`, `${hint}-item`);
    return /^[a-zA-Z0-9-]+$/.test(expr) ? expr : this.define(`${hint}-item`, expr);
  }

  private literalFor(value: unknown, path: string): string {
    if (value === undefined) {
      throw new SchemaError("cannot encode undefined as a JSON literal", path);
    }
    if (typeof value === "number" && !Number.isFinite(value)) {
      throw new SchemaError("cannot encode a non-finite number as a JSON literal", path);
    }
    return this.seq(quoteLit(JSON.stringify(value)), this.ws());
  }
}

// --- helpers ---------------------------------------------------------------

function boundsSuffix(min: number, max: number | null): string {
  if (min === 0 && max === null) return "*";
  if (min === 1 && max === null) return "+";
  if (min === 0 && max === 1) return "?";
  if (max === null) return `{${min},}`;
  if (min === max) return `{${min}}`;
  return `{${min},${max}}`;
}

function intOrDefault(v: unknown, dflt: number, path: string, what: string): number {
  if (v === undefined) return dflt;
  if (typeof v !== "number" || !Number.isInteger(v) || v < 0) {
    throw new SchemaError(`${what} must be a non-negative integer`, path);
  }
  return v;
}

function kvName(hint: string, key: string): string {
  const base = sanitizeName(key);
  return hint === "root" ? base : `${sanitizeName(hint)}-${base}`;
}

function sanitizeName(raw: string): string {
  const cleaned = raw
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return cleaned === "" ? "sub" : cleaned;
}

function decodePointerSegment(segment: string): string {
  return segment.replace(/~1/g, "/").replace(/~0/g, "~");
}

function resolvePointer(doc: unknown, ref: string, path: string): unknown {
  const parts = ref.slice(1).split("/").filter((p) => p !== "");
  let current: unknown = doc;
  for (const raw of parts) {
    const key = decodePointerSegment(raw);
    if (Array.isArray(current)) {
      current = current[Number.parseInt(key, 10)];
    } else if (typeof current === "object" && current !== null) {
      current = (current as SchemaObject)[key];
    } else {
      current = undefined;
    }
    if (current === undefined) {
      throw new SchemaError(`cannot resolve $ref "${ref}"`, path);
    }
  }
  return current;
}

/**
 * Convert a parsed JSON Schema document into GBNF text.
 * Throws {@link SchemaError} for schemas that cannot be expressed;
 * collects a note per ignored keyword instead of silently dropping it.
 */
export function schemaToGbnf(
  schema: unknown,
  options: ConvertOptions = {}
): ConvertResult {
  const emitter = new Emitter(schema, options);
  emitter.setRoot(emitter.visit(schema, "#", "root"));
  return { grammar: emitter.render(), notes: emitter.notes };
}
